apiVersion: v1
data:
  version: {{ .Values.image.tag }}
kind: ConfigMap
metadata:
  name: "{{ printf \"%s-%s\" .Values.image.repository .Values.image.tag }}"
  namespace: {{ .Values.namespace.name }}
